title: Codioso Blog
description: Collection of coding snippets and ideas
permalink: /:slugified_categories/:title/
safe: true

date_format: "%b %-d, %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
